<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Login</title>
    </head>
    <body>
        <h1>INICIO DE SESION</h1>
        <form action="index.php?controller=usuarios&action=login">
            <label>NOMBRE</label><input name="nombre" type="text" /><br>
            <label>CONTRASEÑA</label><input namoe="password" type="password"/><br>
            <input type="submit" value="iniciar sesion" />
        </form>
    </body>
</html>
